### ISSUE TITLE
Visual studio Error

### ISSUE THREAD

**Issue by KevinRommens** [elitepleb/that_one#3]
error  : Project "C:\Users\kevin\Desktop\Sources\that_one-master\that one solution\That one\That one.vcxproj" could not be found.

The vcxproj is in the file together with everything else...

**Comment by elitepleb** [comment]
sorry for the late reply, i did not have a chance to test if the project still worked when compiled as i described in the readme.

it still works and i don't feel like helping a girl anime avatar guy whose three repositories feature the word "paste".

**Comment by KevinRommens** [comment]
> sorry for the late reply, i did not have a chance to test if the project still worked when compiled as i described in the readme.
> 
> it still works and i don't feel like helping a girl anime avatar guy whose three repositories feature the word "paste".

bruh
