### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by HeXz69** [elitepleb/that_one#6]
after the first game as the map changes the game gets crash

**Comment by elitepleb** [comment]
Works on my machine, so let's make this a learning opportunity.
Any chance of you debugging the crash cause?
![Untitled](https://user-images.githubusercontent.com/15345338/76664330-a7026400-658c-11ea-8c3e-a91707194a2a.png)

**Comment by HeXz69** [comment]
2 razy uruchomiłęm debugger,oto rezultat(przepraszam za język polski w visual studio)
![Screenshot_52](https://user-images.githubusercontent.com/61068958/76669359-92719c00-658b-11ea-909a-18c7ab3b6489.png)
![Screenshot_53](https://user-images.githubusercontent.com/61068958/76669361-930a3280-658b-11ea-824a-5e21ecde8e4d.png)
![Screenshot_54](https://user-images.githubusercontent.com/61068958/76669363-930a3280-658b-11ea-91e4-7e9f4abc14f4.png)
![Screenshot_55](https://user-images.githubusercontent.com/61068958/76669364-93a2c900-658b-11ea-85d9-06ed434737c2.png)

**Comment by elitepleb** [comment]
It's something unrelated to the cheat, no idea what though.
Sorry, but i can't do anything to help
